Projeto2/Models/ErrorViewModel.cs
namespace Projeto2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Projeto2/Models/Produto.cs
namespace Projeto2.Models
{
    public class Produto
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao{ get; set; }
        public decimal Preco { get; set; }
    }
}

Projeto2/Models/Usuario.cs
namespace Projeto2.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
    }
}

Projeto2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Projeto2.Models;
using System.Diagnostics;

namespace Projeto2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

    

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Projeto2/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using Projeto2.Models;
using Projeto2.Repositorio;

namespace Projeto2.Controllers
{
    public class ProdutoController : Controller
    {
        public readonly ProdutoRepositorio _produtoRepositorio;

        public ProdutoController(ProdutoRepositorio produtoRepositorio)
        {
            _produtoRepositorio = produtoRepositorio;
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(Produto produto)
        {
            if (ModelState.IsValid)
            {
                _produtoRepositorio.AdicionarProduto(produto);
            }

            return View();
        }
    }
}

Projeto2/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Projeto2.Models;
using Projeto2.Repositorio;

namespace Projeto2.Controllers
{
    public class UsuarioController : Controller
    {   
        //Construtor
        private readonly UsuarioRepositorio _usuarioRepositorio;

        public UsuarioController(UsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string email, string senha)
        {
            var usuario = _usuarioRepositorio.ObterUsuario(email);

            if (usuario != null && usuario.Senha == senha)
            {
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("", "Email ou senha inválidos.");

            return View();
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _usuarioRepositorio.AdicionarUsuario(usuario);
                return RedirectToAction("Login");
            }

            return View(usuario);
        }
    }
}

Projeto2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <img src="~/image/logo.png" alt="logo"/>
    <h1 class="display-4">Bem vindo ao Anu Viagens</h1>
    <p id="tagline">Um brasil que você nunca imaginou</a>.</p>
</div>

Projeto2/Views/Produto/Cadastro.cshtml
@model Projeto2.Models.Produto;
@{
	ViewData["Title"] = "Registra Produto";
}
<h2>Registra Produto</h2>

<form asp-action="Cadastro" id="Cadastro" method="post">
	<div>
		<label>Nome:</label> <br />
		<input asp-for="Nome" required />
	</div>
	<div>
		<label>Descrição:</label> <br />
		<input asp-for="Descricao"  required />
	</div>
	<div>
		<label>Preço:</label> <br />
		<input asp-for="Preco"  required />
	</div> 
	<br />
	<button type="submit">Cadastrar Produto</button>
</form>

Projeto2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projeto2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white"  asp-area="" asp-controller="Home" asp-action="Index">Anu Viagens</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Usuario" asp-action="Cadastro">Cadastro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Produto" asp-action="Cadastro">Cadastra Produto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted">
        <div class="container">
            &copy; 2025 -Anu Viagens
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Projeto2/Views/Usuario/Cadastro.cshtml
@model Projeto2.Models.Usuario;
@{
	ViewData["Title"] = "Cadastro";
}
<h2>Cadastro</h2>

<form asp-action="Cadastro"  id=Cadastro method="post">
	<div>
		<label>Nome</label> <br />
		<input asp-for="Nome" required />
	</div>
	<div>
		<label>Email</label> <br />
		<input asp-for="Email" type="email" required />
	</div>
	<div>
		<label>Senha</label> <br />
		<input asp-for="Senha" type="password" required />
	</div>
	<br />
	<button type="submit">Novo Cadastrado</button>
</form>

Projeto2/Views/Usuario/Login.cshtml
@model Projeto2.Models.Usuario;
@{
    ViewData["Title"] = "Login";
}
<h2>Login</h2>
<form asp-action="Login" id="Cadastro" method="post">
	<div>
		<label>Email</label><br />
		<input type="email" name="email" required />
	</div>
	<div>
		<label>Senha</label><br />
		<input type="password" name="senha" required />
	</div>
	<br />
	<button type="submit">Login</button>
</form>